apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bindrole
subjects:
- kind: ServiceAccount
  name: my-serviceaccount 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
